# filename: templates/csharp-basic-webserver/manifests/kustomization.yaml
# Kustomize configuration with ASP.NET Core specific metadata
# Maintains same structure as Python template with these additions:
# - Health check annotations (commented)
# - ASP.NET Core specific labels

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app: "urb-dev-csharp-hello-world"
  owner: "terchris"
  techstack: "aspnet-core"
  managed-by: argocd

commonAnnotations:
  description: "ASP.NET Core web server deployed via Urbalurba infrastructure"
  repository: "https://github.com/terchris/urb-dev-csharp-hello-world"
  # Optional ASP.NET Core specific annotations:
  # app.kubernetes.io/runtime: dotnet
  # app.kubernetes.io/version: 8.0