# filename: templates/csharp-basic-webserver/.github/workflows/urbalurba-build-and-push.yaml
name: Build and Push

on:
  push:
    branches: [main]
    paths-ignore:
      - 'manifests/**'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/WebApplication/WebApplication.csproj

      - name: Publish Application
        run: |
          dotnet publish src/WebApplication/WebApplication.csproj \
            -c Release \
            -o published \
            --no-restore \
            -p:AssemblyVersion=${{ github.run_number }} \
            -p:InformationalVersion="${{ github.sha }}"

      - name: Prepare Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s/{{GITHUB_USERNAME}}/${{ github.repository_owner }}/g" manifests/*
          sed -i "s/{{REPO_NAME}}/${{ github.event.repository.name }}/g" manifests/*
        if: always()